### PR TITLE
Collector OpenShift Services

### PR DESCRIPTION
**Pull request by slemrmartin**
**Issue**: https://github.com/RedHatInsights/topological_inventory-api/issues/320

Deployment of Service objects for Collectors. They're exposing port 9394 for ServiceMonitor (prometheus metrics)

---

[RHCLOUD-10951](https://issues.redhat.com/browse/RHCLOUD-10951)

### CODE REVIEW

**Comment by slemrmartin** [comment]
Ready for review, tested on CI (mslemr-test namespace)

**Review by lindgrenj6 — COMMENTED** [review]
Looks good, just some rubocop issues. Will merge once those are fixed. 

Initially I was worried we didn't have the prometheus annotations on the deployment configs, looks like that is not the case :+1:

**Comment by slemrmartin** [comment]
@lindgrenj6 some of rubocop warnings don't make sense in the context. Test kube_client has to be compatible with real kube_client and named arguments can't have _ prefix. 

Other warnings are made in context of the code around the new one. So I rather chose code similar for the other openshift objects. 
Fixing these rubocop issues will make sense only with fixing other methods not related to this PR. If you think it's necessary, it'll be better to fix in following PR.

**Comment by lindgrenj6** [comment]
@slemrmartin sure, I think we should fix them still (maybe just run `rubocop -a`) and have a new PR for it. That way we don't have these issues every time etc. 

The `_prefix` one won't change though, I agree on that one.

**Review by lindgrenj6 — APPROVED** [review]

**Pull request merged**
